language: java

os: linux

sudo: required

jdk:
  - oraclejdk8

script: mvn clean install cobertura:cobertura -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
  - bash <(curl -s https://codecov.io/bash)